"""Beidou agent primitives (pure Python). See ``core`` for the implementation."""

from beidou.primitives.core import (
    CONTRACT_STRIKES,
    FAN_OUT_CAP,
    INBOX_CAP,
    MAX_DEPTH,
    WAIT_CEILING,
    GatewayDeclined,
    Message,
    Orchestrator,
    Peer,
    PrimitiveError,
    ask_user,
    create_team,
    list_peers,
    read_messages,
    report_status,
    send_message,
    terminate_child,
    wait_for_message,
)
from beidou.primitives.mcp import build_mcp_server_for

__all__ = [
    "INBOX_CAP",
    "WAIT_CEILING",
    "FAN_OUT_CAP",
    "MAX_DEPTH",
    "CONTRACT_STRIKES",
    "PrimitiveError",
    "GatewayDeclined",
    "Message",
    "Peer",
    "Orchestrator",
    "send_message",
    "read_messages",
    "wait_for_message",
    "list_peers",
    "ask_user",
    "report_status",
    "create_team",
    "terminate_child",
    "build_mcp_server_for",
]
